/**
 * Firebase configuration — loaded from public/env-config.json at runtime.
 *
 * The env-config.json is generated by scripts/setup-env.js from .env.local.
 * Run: node scripts/setup-env.js
 */

let _configCache: {
  apiKey: string;
  authDomain: string;
  projectId: string;
  storageBucket: string;
  messagingSenderId: string;
  appId: string;
} | null = null;

async function readEnvConfigJson(): Promise<Record<string, string>> {
  // A relative fetch('/env-config.json') resolves against the current page
  // in a browser, but Node's fetch() has no page to resolve it against and
  // throws immediately — meaning this would ALWAYS fail during SSR and
  // silently fall back to an empty config on every server-rendered request.
  // On the server, read the same file straight off disk instead: it's
  // deployed as a static asset right next to the server bundle itself
  // (dist/<app>/browser/env-config.json, sibling to dist/<app>/server/).
  const isNode = typeof process !== 'undefined' && !!process.versions?.node;
  if (isNode) {
    // A non-literal specifier keeps esbuild from trying to statically
    // resolve this Node builtin for the browser bundle (this branch never
    // executes there — `isNode` is false — but esbuild would still fail
    // the browser build if it saw a literal `import('node:fs/promises')`).
    const fsPromisesSpecifier = ['node:fs', 'promises'].join('/');
    const { readFile } = await import(fsPromisesSpecifier);
    const configUrl = new URL('../browser/env-config.json', import.meta.url);
    const text = await readFile(configUrl, 'utf-8');
    return JSON.parse(text);
  }

  const resp = await fetch('/env-config.json');
  if (!resp.ok) {
    throw new Error(`env-config.json responded with ${resp.status}`);
  }
  return resp.json();
}

export async function getFirebaseConfig() {
  if (_configCache) return _configCache;

  try {
    const env = await readEnvConfigJson();
    _configCache = {
      apiKey: env['FIREBASE_API_KEY'] || '',
      authDomain: env['FIREBASE_AUTH_DOMAIN'] || '',
      projectId: env['FIREBASE_PROJECT_ID'] || '',
      storageBucket: env['FIREBASE_STORAGE_BUCKET'] || '',
      messagingSenderId: env['FIREBASE_MESSAGING_SENDER_ID'] || '',
      appId: env['FIREBASE_APP_ID'] || '',
    };
    return _configCache;
  } catch (err) {
    console.error('[Firebase Config] Failed to load env-config.json:', err);
  }

  _configCache = {
    apiKey: '',
    authDomain: '',
    projectId: '',
    storageBucket: '',
    messagingSenderId: '',
    appId: '',
  };
  return _configCache;
}

// Legacy sync accessor — returns cached config or empty defaults.
export const environment = {
  production: false,
  get firebase() {
    return _configCache ?? {
      apiKey: '',
      authDomain: '',
      projectId: '',
      storageBucket: '',
      messagingSenderId: '',
      appId: '',
    };
  },
};
