/**
 * Firebase configuration — loaded from public/env-config.json at runtime.
 *
 * The env-config.json is generated by scripts/setup-env.js from .env.local.
 * Run: node scripts/setup-env.js
 */

let _configCache: {
  apiKey: string;
  authDomain: string;
  projectId: string;
  storageBucket: string;
  messagingSenderId: string;
  appId: string;
} | null = null;

export async function getFirebaseConfig() {
  if (_configCache) return _configCache;

  try {
    const resp = await fetch('/env-config.json');
    if (resp.ok) {
      const env = await resp.json();
      _configCache = {
        apiKey: env.FIREBASE_API_KEY || '',
        authDomain: env.FIREBASE_AUTH_DOMAIN || '',
        projectId: env.FIREBASE_PROJECT_ID || '',
        storageBucket: env.FIREBASE_STORAGE_BUCKET || '',
        messagingSenderId: env.FIREBASE_MESSAGING_SENDER_ID || '',
        appId: env.FIREBASE_APP_ID || '',
      };

      console.log('[Firebase Config]');
      for (const [key, val] of Object.entries(_configCache)) {
        console.log(`  ${key}: ${val ? 'present' : 'MISSING'}`);
      }
      return _configCache;
    }
  } catch (err) {
    console.error('[Firebase Config] Failed to load env-config.json:', err);
  }

  _configCache = {
    apiKey: '',
    authDomain: '',
    projectId: '',
    storageBucket: '',
    messagingSenderId: '',
    appId: '',
  };
  return _configCache;
}

// Legacy sync accessor — returns cached config or empty defaults.
export const environment = {
  production: false,
  get firebase() {
    return _configCache ?? {
      apiKey: '',
      authDomain: '',
      projectId: '',
      storageBucket: '',
      messagingSenderId: '',
      appId: '',
    };
  },
};
